// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiaqF06lZ7TBS-HhhBk8rgX_nyzfWbTpE',
    appId: '1:182308291232:web:84e8618580d9024e773fc5',
    messagingSenderId: '182308291232',
    projectId: 'coach-app-3e5d1',
    authDomain: 'coach-app-3e5d1.firebaseapp.com',
    storageBucket: 'coach-app-3e5d1.firebasestorage.app',
    measurementId: 'G-3HC490SKF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBF16hdYZXtRe45UhNoMgySwe3hfiBccU',
    appId: '1:182308291232:android:1d2b43342b4d4aa5773fc5',
    messagingSenderId: '182308291232',
    projectId: 'coach-app-3e5d1',
    storageBucket: 'coach-app-3e5d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtbXcqsRecK0AsfyH66-2URbPoh7IPcn0',
    appId: '1:182308291232:ios:35005d710abca5a1773fc5',
    messagingSenderId: '182308291232',
    projectId: 'coach-app-3e5d1',
    storageBucket: 'coach-app-3e5d1.firebasestorage.app',
    iosBundleId: 'com.example.coachApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtbXcqsRecK0AsfyH66-2URbPoh7IPcn0',
    appId: '1:182308291232:ios:35005d710abca5a1773fc5',
    messagingSenderId: '182308291232',
    projectId: 'coach-app-3e5d1',
    storageBucket: 'coach-app-3e5d1.firebasestorage.app',
    iosBundleId: 'com.example.coachApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiaqF06lZ7TBS-HhhBk8rgX_nyzfWbTpE',
    appId: '1:182308291232:web:643e7ce1d96ee908773fc5',
    messagingSenderId: '182308291232',
    projectId: 'coach-app-3e5d1',
    authDomain: 'coach-app-3e5d1.firebaseapp.com',
    storageBucket: 'coach-app-3e5d1.firebasestorage.app',
    measurementId: 'G-EXRPB5XXEN',
  );
}
